In [1]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv(r"D:\Downloads/bank.csv")

In [5]:
dataset.head(2)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   
1   56  admin.  married  secondary      no       45      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes

In [6]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [7]:
m = dataset.iloc[:,0:9]
n = dataset.iloc[:,11:13]
o = dataset.iloc[:,14:16]

In [8]:
x = m.join(n)
x = x.join(o)

In [9]:
x = x.values
y = dataset.iloc[:,16:].values

In [10]:
x[0]

array([59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
       'unknown', 1042, 1, 0, 'unknown'], dtype=object)

In [11]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [13]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,12])],remainder ="passthrough")
x = ct.fit_transform(x)

In [14]:
ct1 = ColumnTransformer([("one",OneHotEncoder(),[0])],remainder ="passthrough")
y = ct1.fit_transform(y)

In [15]:
x[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 1042, 1, 0], dtype=object)

In [16]:
y[70]

array([0., 1.])

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [20]:
categorical = Sequential()

In [21]:
x_train.shape

(8929, 37)

In [22]:
y_train.shape

(8929, 2)

In [23]:
categorical.add(Dense( units= 37, kernel_initializer= "random_uniform", activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [24]:
categorical.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [25]:
categorical.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [26]:
categorical.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [27]:
categorical.add(Dense( units= 2, kernel_initializer= "random_uniform", activation="softmax"))

In [28]:
categorical.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics=["accuracy"])

In [29]:
categorical.fit(x_train, y_train, epochs = 350)

Epoch 1/350
8929/8929 [==============================] - 1s 76us/sample - loss: 0.4642 - acc: 0.7786
Epoch 2/350
8929/8929 [==============================] - 0s 50us/sample - loss: 0.4217 - acc: 0.8131
Epoch 3/350
8929/8929 [==============================] - 0s 54us/sample - loss: 0.4150 - acc: 0.8191
Epoch 4/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.4098 - acc: 0.8197
Epoch 5/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.4072 - acc: 0.8201
Epoch 6/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.4045 - acc: 0.8200
Epoch 7/350
8929/8929 [==============================] - 0s 52us/sample - loss: 0.4011 - acc: 0.8214
Epoch 8/350
8929/8929 [==============================] - 1s 57us/sample - loss: 0.3984 - acc: 0.8217
Epoch 9/350
8929/8929 [==============================] - 1s 58us/sample - loss: 0.3972 - acc: 0.8225
Epoch 10/350
8929/8929 [==============================] - 0s 56us/sample - loss: 0.3951 - a

8929/8929 [==============================] - 0s 53us/sample - loss: 0.2553 - acc: 0.8955
Epoch 82/350
8929/8929 [==============================] - 0s 54us/sample - loss: 0.2488 - acc: 0.8955
Epoch 83/350
8929/8929 [==============================] - 0s 53us/sample - loss: 0.2533 - acc: 0.8949
Epoch 84/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.2525 - acc: 0.8969
Epoch 85/350
8929/8929 [==============================] - 0s 52us/sample - loss: 0.2545 - acc: 0.8953
Epoch 86/350
8929/8929 [==============================] - 0s 56us/sample - loss: 0.2475 - acc: 0.8997
Epoch 87/350
8929/8929 [==============================] - 1s 58us/sample - loss: 0.2499 - acc: 0.8982
Epoch 88/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.2423 - acc: 0.9007
Epoch 89/350
8929/8929 [==============================] - 0s 52us/sample - loss: 0.2457 - acc: 0.8983
Epoch 90/350
8929/8929 [==============================] - 0s 52us/sample - loss: 0.2452 - acc: 

8929/8929 [==============================] - 1s 61us/sample - loss: 0.1838 - acc: 0.9256
Epoch 161/350
8929/8929 [==============================] - 0s 54us/sample - loss: 0.1844 - acc: 0.9262
Epoch 162/350
8929/8929 [==============================] - 0s 53us/sample - loss: 0.1858 - acc: 0.9236
Epoch 163/350
8929/8929 [==============================] - 0s 55us/sample - loss: 0.1820 - acc: 0.9287
Epoch 164/350
8929/8929 [==============================] - 0s 56us/sample - loss: 0.1827 - acc: 0.9242
Epoch 165/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.1845 - acc: 0.9241
Epoch 166/350
8929/8929 [==============================] - 1s 57us/sample - loss: 0.1829 - acc: 0.9252
Epoch 167/350
8929/8929 [==============================] - 1s 57us/sample - loss: 0.1797 - acc: 0.9291
Epoch 168/350
8929/8929 [==============================] - 1s 57us/sample - loss: 0.1811 - acc: 0.9303
Epoch 169/350
8929/8929 [==============================] - 1s 64us/sample - loss: 0.203

8929/8929 [==============================] - 1s 61us/sample - loss: 0.1615 - acc: 0.9440
Epoch 240/350
8929/8929 [==============================] - 1s 63us/sample - loss: 0.1506 - acc: 0.9460
Epoch 241/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.1517 - acc: 0.9409
Epoch 242/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.1711 - acc: 0.9459
Epoch 243/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.1510 - acc: 0.9405
Epoch 244/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.1519 - acc: 0.9457
Epoch 245/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.1610 - acc: 0.9415
Epoch 246/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.1465 - acc: 0.9453
Epoch 247/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.1482 - acc: 0.9412
Epoch 248/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.151

8929/8929 [==============================] - 1s 61us/sample - loss: 0.1385 - acc: 0.95620s - loss: 0.0881 - acc:
Epoch 318/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.1272 - acc: 0.9574
Epoch 319/350
8929/8929 [==============================] - 1s 62us/sample - loss: 0.1327 - acc: 0.9550
Epoch 320/350
8929/8929 [==============================] - 1s 62us/sample - loss: 0.1340 - acc: 0.9559
Epoch 321/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.1201 - acc: 0.9572
Epoch 322/350
8929/8929 [==============================] - 1s 62us/sample - loss: 0.1246 - acc: 0.9554
Epoch 323/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.1298 - acc: 0.9561
Epoch 324/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.1224 - acc: 0.9543
Epoch 325/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.1416 - acc: 0.9549
Epoch 326/350
8929/8929 [==============================] - 1s 6

In [30]:
ypred = categorical.predict(x_test)

In [31]:
ypred

array([[1.0000000e+00, 0.0000000e+00],
       [1.2911717e-08, 1.0000000e+00],
       [1.0000000e+00, 8.5428228e-16],
       ...,
       [1.1930526e-03, 9.9880695e-01],
       [1.0000000e+00, 0.0000000e+00],
       [9.9928719e-01, 7.1281340e-04]], dtype=float32)

In [32]:
ypred = ypred>0.5

In [33]:
deposit = ["No","Yes"]
yp = categorical.predict(sc.transform(ct.transform([[59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
       'unknown', 1042, 1, 0, 'unknown']])))
prediction = deposit[np.argmax(yp)]
prediction

'Yes'

In [34]:
dataset.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes